
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  adapter: postgresql
  encoding: unicode
  host: ec2-23-23-225-12.compute-1.amazonaws.com
  port: 5432
  database: d624e2ntt8nbqg
  username: wyayqqjntdlylz
  password: e1033192545456a16901b27292c0033a351eaa9a298417aff567f834ac3666f6
