
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

production:
  adapter: postgresql
  encoding: unicode
  host: ec2-54-163-254-143.compute-1.amazonaws.com
  port: 5432
  database: d2na1fbcpaag6q
  username: hwyqpurfgifioa
  password: 95327a39b4553721cb3c60d51dc00733368cd720cc4c443f3d06a42e14900479
